### ISSUE TITLE
error when editing work party

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#118]
I tried to edit https://cs9.salesforce.com/a2eK0000000wNzF to change its Work Party Type, but got the following error when I tried to save:

Error:Apex trigger WTA_VMS_Work_Party_After caused an unexpected exception, contact your administrator: WTA_VMS_Work_Party_After: execution of AfterUpdate caused by: System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Contact already has a registration for this workparty: []: Class.WTA_VMS_WP_Manage_CLRegistration.manageCLWorkPartyRegistrations: line 45, column 1

**Comment by davisagli** [comment]
I get a similar error when I try to update a registration with status = Registered to change its status to Cancelled:

SalesforceMalformedRequest: Malformed request https://cs9.salesforce.com/services/data/v29.0/sobjects/WP_Registration__c/a2oK0000000qBm3. Response content: [{u'errorCode': u'CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY', u'fields': [], u'message': u'WTA_VMS_Work_Party_After: execution of AfterUpdate\n\ncaused by: System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Contact already has a registration for this workparty: []\n\nClass.WTA_VMS_WP_Manage_CLRegistration.manageCLWorkPartyRegistrations: line 45, column 1\nTrigger.WTA_VMS_Work_Party_After: line 20, column 1'}]

**Comment by mscholtz** [comment]
@drewpiston I think this might be one for you.  Looks to me like the problem is line 33 of WTA_VMS_WP_Manage_CLRegistration - that's just doing a query on WP with no WHERE clause, where I think you meant to requery just the WPs from the trigger?  So then it's trying to add a leader registration to every WP in the database, quickly leading to duplicates which trip the validation.  Is this something you could look at first thing Monday?  Thanks!

**Comment by drewpiston** [comment]
Well spotted, @mscholtz !  This is ready for review.

**Comment by davisagli** [comment]
I'm now able to make both changes without error. Thanks for the quick fix.

**Comment by mscholtz** [comment]
Thanks, @drewpiston
