### ISSUE TITLE
Work party will auto calculate end date when start date changes

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#140]
When a work party has the start date change the end date should automatically be calculated based on the Work Party Type and the new start date.  Typically this is needed just after cloning a work party when a new start date is entered.

The End Date still need to be manually changed in case there is a variation from the duration (default length) set on the Work Party Type.

**Comment by mscholtz** [comment]
I think this should be a story.  Because
1) this is a new requirement
2) I think we need to think through carefully exactly when this should happen.  If we make this too liberal, we run the risk of changing the end date in circumstances where the user didn't want it or expect it.  How do we know when there's supposed to be an exception?

**Comment by WaBirder57** [comment]
We have tried to think about those exceptions and while they may exist those are the situations where staff will be checking/setting the end date manually.

Keeping this simple and just doing that calculation automatically will be a big big help.  We can deal with the odd case.  Typically those are BCRTs where staff are well aware that they are “different”.

Thus, I think the odds of an error are much higher if this is not automatic than if it isn’t, event with out exception handling.

**Comment by mscholtz** [comment]
OK I would suggest that we at least set this up so that if both the start
and end dates are change in one transaction that it doesn't try to set the
end date.  It would only do so if the user changed just the start date and
not the end date.  Otherwise I could see this being really frustrating at
times.

Sound OK?


On Thu, Jun 11, 2015 at 1:08 PM, Charles Kahle <notifications@github.com>
wrote:

> We have tried to think about those exceptions and while they may exist
> those are the situations where staff will be checking/setting the end date
> manually.
>
> Keeping this simple and just doing that calculation automatically will be
> a big big help. We can deal with the odd case. Typically those are BCRTs
> where staff are well aware that they are “different”.
>
> Thus, I think the odds of an error are much higher if this is not
> automatic than if it isn’t, event with out exception handling.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/140#issuecomment-111262407>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by WaBirder57** [comment]
Yes, that sounds smart.

 

Thanks

 

Charlie

**Comment by mscholtz** [comment]
@drewpiston and how about this one too.  both this and the previous one are about ineriting from WP Type which I think you've worked on... 
please see discussion on this ticket

**Comment by drewpiston** [comment]
This is ready for testing.

**Comment by WaBirder57** [comment]
This seems to work.  Change the start date for a work party.  After it is saved the end date is updated to a value based on the start date and WP Type trip length.

**Comment by WaBirder57** [comment]
After additional testing we find that this isn't working all the time.  If the Work party Start date is edited to a date in the future and end date is not changed there will be an error on save:

Error:The Work Party Start can not be earlier than its End. Please check the Start and End dates and time.

Because the WP can't be saved in this case the End Date can't be calculated based on the WP Type duration.  If need be, remove the validation rule for Start Date being less than or equal to end date.

**Comment by drewpiston** [comment]
Hi Charlie,

I think I have a better solution for this.  The validation rule now only applies if the End Date has been manually changed.

Give it a whirl and let me know what you think.

Cheers,
 Drew

**Comment by WaBirder57** [comment]
Yes, seems to work great.  I like this new approach.
