### ISSUE TITLE
wrong Region picklist values?

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#17]
Isn't the picklist for WTA Region on a trail segment (https://cs10.salesforce.com/00NJ0000001fvMe?setupid=CustomObjects) supposed to have the same values as the "Region" dropdown in the hiking guide (https://www.wta.org/go-hiking/hikes)?

**Comment by WaBirder57** [comment]
David,

 

No these are not the same.

 

The SF Trail Schema will have a Trail Segment which is mapped to a WTA region.

 

Several Trail Segments will be mapped to a SF Hike record.  This SF Hike record will be linked to a Hiking Guide Hike.

 

The hiking guide “regions” are artifacts of the Mountaineer books as well as how people look for hikes.  For example Mt Rainier and Issaquah Alps are Hiking Guide Regions – not WTA regions.

 

Charlie

**Comment by davisagli** [comment]
Okay. And the WTA Region of the Trail Segment is the one which should be shown as a facet in the work party search, right?

I'm asking partly because the list of WTA Regions in Salesforce is currently abbreviated (PSM, EA WA, etc). That means we need a separate hardcoded list in VMS to convert the abbreviations to something that's meaningful to the user. I'm wondering if we can stop using abbreviations in Salesforce. Then VMS can just display the regions that were indexed from Salesforce, and it'll be a bit more straightforward to adjust the list of regions if and when that needs to happen.

**Comment by WaBirder57** [comment]
David and Matthew,

 

Great question and we are doing a review of this and how best to pull these together.  I’ll need to design a schema for this (see draft below).  Sorry for a more lengthy answer but I want those on this email thread to understand where we are in this discussion.  David I have tried to get to your answers at the bottom.

 

Goals:

-          Make is easy to have consistent internal reporting by WTA Region for Hiking Guide data (e.g. Trip Reports/WTA Region) as well as Work Party data (WP /WTA Region).

-          Make it easy to “adjust”  regions in one place.

-          Have geographic area descriptions that are meaningful to both hikers and volunteers as well as consistent between Hiking Guide and Work Party.

 

We have:  

Hiking Guide Regions

Hiking Guide Sub regions



 

We have WTA Regions (used internally for reporting).  These regions are defined by Zip codes (in Apex code at this point).  Currently work parties have been identified by these regions (see current web site) but we will be changing this so that it is consistent with our Hiking Guide.

 

To do this in Salesforce here is a draft table schema.

 



 

David: To answer your questions:

-          We should have a SF Table with a Short and Long name for a WTA Region.  Useful for SF reporting

-          A Trail Segment will have a link to a Hiking Guide Sub Region (not to a WTA region as in the current design).  This is a KEY point I need others to help think through the implications of this, as well as this whole design.

-          The facet search for Volunteers to find Work Parties should use the Hiking Guide Region.  Note that if there are no work party results returned for a selected region(s) – that is non published for the public to see – we should return a customized page with a message like “Sorry no current work parties scheduled in this region. If you would like to suggest work that is needed please contact xyz@percolator.com

 

After all this sounds like we may need a new story?

 

Charlie

**Comment by davisagli** [comment]
Here are my thoughts on your proposal:
1. I don't understand why you want to keep using an abbreviated form of the WTA Region. But, if that is important for reporting, it's okay with me. It sounds like VMS doesn't need to do anything with this value; it's just for reporting.
2. It sounds like we need to add a new field to Trail Segment so it can be associated with a hiking guide region & subregion. I think it might make sense to make Hiking Guide Region and Hiking Guide Subregion be picklist fields on Trail Segment, rather than adding a new object to represent regions. But I'll defer to Percolator's opinion.
3. Typically with a faceted search UI, you simply don't show the options that would result in 0 results. That's the easiest thing for us to do, because VMS currently only knows about the regions that have been indexed on work parties in elasticsearch, not about all possible regions. And I think this is a better UX, because you don't lead people to click on something that is a dead end. However if you really want to show the regions that have no results, so that you can prompt people to suggest work that is needed, then yes, I think that's a new story.

**Comment by WaBirder57** [comment]
Quick answers:

 

1)      – yes used for internal reporting, short and long name would be useful not just the abbreviation.

2)      I look to Chris/Percolator to respond.  We have a TrailSegment.WTARegion field now, perhaps that can become the WTASubregion.

3)      I think your approach would be ok, only list options that return results. But we may want to show the breadth of places we do or have done work.  Hedging my bets but go with your approach.

 

Charlie

**Comment by mscholtz** [comment]
Chris is working on this, and will be meeting w/ Charlie early next week

**Comment by davisagli** [comment]
Updates from standup today:
- trail segments now have fields for hiking guide region and subregion
- we should pull the trail segment that is marked as the primary one for a work party
- Charlie says we only need to be able to filter by the region (not subregion) in faceted search, to avoid a long list

**Comment by WaBirder57** [comment]
Note the Hiking Guide entry has the Region and Sub Region, we don’t need to store that in the Trail Segment.  We can pull this info from the Trail Segments “primary” hiking guide entry.  The Hiking Guide will be the one and only place this data is stored for WTA.  If Region or Sub Region changes for a Hiking Guide entry, the associated Trail Segments will get the new names.  Note that these fields currently exist in Plone and we can use them now.

 

The faceted search should only use the Region (not sub-region).

 

One trick to all this is there will be Trail Segments created where there isn’t a hiking guide entry.  In that case we want to “stub out” an unpublished hiking guide entry (for later completion).  I guess this can be a manual process in plone unless there was a way from VMS to create a new Plone hiking guide entry when needed.

 

NOTE: I am not talking about the WTA Region.  Hiking Guide entries do not have this WTA Region field so that needs to be in the Trail Segment table.

**Comment by davisagli** [comment]
No, we can't pull the Region/Subregion from the hiking guide in Plone if we want it to be included in the work party index. That would make the indexing very complicated.

**Comment by mscholtz** [comment]
@WaBirder57 agree with David here.  I think this wants to be stored in SF for architectural reasons.  If we want to come up with a way to periodically sync it from Plone to Trail Segment records in SF, we could talk about that.  But that would need to be a new story, and might not be a small one.

**Comment by WaBirder57** [comment]
Is it practical to have the Region and Sub Region pulled into the Trail Segment when the Hiking Guiding URL field is entered or updated in the Trail Segment?

**Comment by mscholtz** [comment]
That's possible.  That won't help it stay in sync if the Region is changed
on the hiking guide side, though.
However we would want to pull it off, it would be a story.  So I'd say if
syncing is something you want, or even want to consider seriously, go ahead
and write a story for it.  We can figure out the mechanics later.

On Wed, Mar 25, 2015 at 4:31 PM, Charles Kahle <notifications@github.com>
wrote:

> Is it practical to have the Region and Sub Region pulled into the Trail
> Segment when the Hiking Guiding URL field is entered or updated in the
> Trail Segment?
>
>
>
> From: Matthew Scholtz [mailto:notifications@github.com]
> Sent: Wednesday, March 25, 2015 4:11 PM
> To: washingtontrails/vms
> Cc: Charles Kahle
> Subject: Re: [vms] wrong Region picklist values? (#17)
>
>
>
> @WaBirder57 <https://github.com/WaBirder57> agree with David here. I
> think this wants to be stored in SF for architectural reasons. If we want
> to come up with a way to periodically sync it from Plone to Trail Segment
> records in SF, we could talk about that. But that would need to be a new
> story, and might not be a small one.
>
> —
> Reply to this email directly or view it on GitHub <
> https://github.com/washingtontrails/vms/issues/17#issuecomment-86249025>
> . <
> https://github.com/notifications/beacon/AH7VjpJ18x4QVYvR464o0Igm9ZkTAo1Kks5n4zgDgaJpZM4DeFrt.gif>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/17#issuecomment-86252001>.
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by davisagli** [comment]
The pyramid app now indexes the hiking guide region from the work party's trail segment(s), instead of the WTA region.
