### ISSUE TITLE
Youth Registration Policy - Need staff override for Adult leaders and other exceptions to age rule

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#208]
User Story #119: Youth Registration Policy.  General participants may have to be under 18, but our leaders will still be over 18. Also, staff should be able to override this age restriction, even for general participants.

When assigning the Crew Leader for a "Youth Only" WP you get the following error message:

Error:Apex trigger WTA_VMS_Work_Party_After caused an unexpected exception, contact your administrator: WTA_VMS_Work_Party_After: execution of AfterUpdate caused by: System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, You cannot register an Adult for a Youth Only Work Party or a Youth for an Adult only Work Party.: []: Class.WTA_VMS_WP_Manage_CLRegistration.manageCLWorkPartyRegistrations: line 45, column 1

**Comment by davisagli** [comment]
Since you want staff to be able to override the age restriction, I think that means we should not check the registrant's age at all when a registration is added or edited in Salesforce, if the age restriction is "Youth Only." The age restriction should only apply for registrations being made via the pyramid app, and only for registrants with a work party role of Volunteer (not ACL) ... though youth work parties will usually have "ACL Self-Registration" unchecked, so ACLs won't be able to register via the pyramid app anyway.

Did I get that right?

What if the age restriction is "adult only"? Should we enforce that one in Salesforce, or only for registrations via the pyramid app?

**Comment by WaBirder57** [comment]
Yes this sounds correct for both the Youth Only and Adult Only work parties.  That is don't have any Staff restrictions in Salesfroce.

**Comment by davisagli** [comment]
Okay. I edited the validation rule which checks the age restriction in Salesforce to make it inactive: https://cs9.salesforce.com/03dK0000000Dum7?setupid=CustomObjects

I also adjusted the age check in the pyramid app so it's only checked when registering as a volunteer, not as an ACL.

This is ready for you to test again.

**Comment by mscholtz** [comment]
This seems OK for now if not ideal.  Ideally, overrideable would not necessarily equal no controls at all.  i.e. the best UI here might be to warn staff that they were about to register a non-youth (and non-leader) for a youth WP in SF, and give them the option to override.  That would ensure it is deliberate, and not just an oversight.  However, this would require some custom SF UI to pull off, so wouldn't be a tiny story.  Charlie, feel free to write a separate story for that if you want that included, otherwise this seems like a decent compromise for now.

**Comment by ebskopin** [comment]
works
