### ISSUE TITLE
Work party registration confirmation email - set based on WP Type

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#210]
When an individual registers for a Work Party they get a confirmation email using the SF Email Template "VMS Registration Confirmation Email".  It appears that this single template is used for all Work Party Types.  Is this true?  

Can we change this so that, as with the other Work Party Email Templates, these are defined based on the Work Party Type?  See the following work party type fields as examples:
- Email Template Group
- Email Template Generic 	 
- Email Template My Backpack	 	 
- Email Template Thank you

**Comment by mscholtz** [comment]
@WaBirder57 are you saying we need separate confirmation email for MBP vs non-MBP vs group, like we have for the reminders?  Or are you saying each WP Type would only use one confirmation template but it would vary by WP type?

Either way, can you explain why this is needed?  We did this for the reminder emails because of the differences in how we would want to handle required forms and how they would complete them (see story 49).  Not entirely clear why we need the confirmations to be non-boilerplate.

Thanks!

**Comment by WaBirder57** [comment]
@mscholtz The confirmation email that volunteers get when they sign up for a work party will need to contain all the details specific to that Work Party Type.  This includes info and links to the forms etc. In may regards the confirmation will be similar to the reminder email.

**Comment by mscholtz** [comment]
If we need required document status/links like in the confirmation email, I think this is going to have to be completely re-done as a VF template.  In which case we probably should write a story for it, to include that and the need for the separate fields on WPT.  You want to write that, Charlie?  

We didn't do it that way to begin with because the email text we were given did not include that.  But we can of course do it now if that's what's needed.

**Comment by mscholtz** [comment]
@WaBirder57 just checking in on this.  See my previous comment.  Should I write a story for this?

**Comment by mscholtz** [comment]
@WaBirder57 bump.. we still need some guidance here.

**Comment by WaBirder57** [comment]
What we are looking for is a Volunteer Registration confirmation email template that is different for each Work Party Type.  Thus for a BCRT or Vol Vac we can include different information that would be contained in the Day Work party registration email conformation.  If we have a Crew Leader College Work Party Type, this registration confirmation would also have very different email.

**Comment by mscholtz** [comment]
@WaBirder57  Does it still need to contain links to required documents, as you specified in a comment above?
Either way, I don't think we have time to get this done this week, but it's even more time-consuming if we need to include required documents.

**Comment by WaBirder57** [comment]
No, doesn't need links to required documents.  We can now point folks to their My Backpack to check status and complete these.

**Comment by WaBirder57** [comment]
I think hat we need is a new field on the WP Type to hold the ID for the Registration Thank you email.  Also, the Work Flow that sends the registration email Thank You should be updated to use the email template for the corresponding WPT.

Here is a screen shot of the existing fields where we need to add this new one.
![wptemailtemplates](https://cloud.githubusercontent.com/assets/8312206/10489527/58ca05ae-7252-11e5-97af-a3019cb667f9.JPG)

**Comment by mscholtz** [comment]
If we are using Workflow to send the email, then just FYI we can't pull the template by ID in the same way as we do in apex code.   So we could still specify it in the way you describe, but might be better to just have a picklist with names, and effectively map those to the templates using the WF rules themselves (b/c we'll need one rule per template instead of a single rule).  We might actually want to use Process Builder instead (shudder..) since that should be able to do it w/ one process instead of multiple rules

**Comment by WaBirder57** [comment]
Matthew, sorry I don't mean to be prescribing how best to implement this, you are best at that.   We just really need to have the ability to send various WP Registration Thank you messages based on the Work Party Type.  If it would be helpful to see examples based on WP Type I can get our Trail Team to work on that.

**Comment by mscholtz** [comment]
@WaBirder57 @ebskopin Heard from Karen that Elliot and Rebecca are going to work through some details of how these emails need to look.  My suggestion is that I will hold off on this until that's done.  If it turns out that the differences are small, it may be that we will be able to use a single template, in which case this would be much quicker to implement.

**Comment by mscholtz** [comment]
@ebskopin I reviewed Julie's templates (https://docs.google.com/document/d/1sdF393-ouV3cJyaYdqa8X1v4_9Yq96yNKWF0ECyS9mU/edit) and my initial reaction is that as it stands these probably should be separate templates, as they're just different enough that it would be tricky to do it with one.  

However, there are several small differences that I'm not sure are intentional/necessary.  Knowing how careful Julie is, they probably are, but wanted to double check that you guys really need:

* FAQ and Trail Work Guide links in different places
* different verbiage in the opening paragraph
* different verbiage in the "please review" paragraph
* What to Wear and What to Bring sections in general template only, missing or replaced w/ links in the VV and BCRT ones

The other big question is whether we still need different templates for the 4 categories charlie outlines in the first comment here.  Julie thinks we don't need separate tempates for MBP vs guest.  But do we still need a separate one for group participants?   And what is "Email Template Thank You"?

**Comment by ebskopin** [comment]
I took a look over the templates that Julie put together and I would say that all of the differences are intentional. It would certainly seem like these should each be separate templates as outlined.

I agree with Julie that we don't really need separate MBP & guest e-mails and I would also say that we don't need a separate e-mail for guests (it would be hard to make things more explicit to them that they already are...). I'm assuming that the "E-mail Template Thank-you" is a mistake in reference to the thank-you e-mail, but I'm not totally sure about that.

**Comment by mscholtz** [comment]
@ebskopin you said "we don't really need separate MBP & guest e-mails and I would also say that we don't need a separate e-mail for guests".
Did you mean to say "we don't need a separate email for groups"?

**Comment by ebskopin** [comment]
Yeah, I intended to say groups.  I don't think the e-mail needs to differ for the respective users.

**Comment by mscholtz** [comment]
@drewpiston folder w/ templates: https://drive.google.com/folderview?id=0B9Z_h99_tSEyLUxiVC0yc2lBUW8&usp=sharing

**Comment by drewpiston** [comment]
Made some good progress on this, some notes:

1. The login link points to the real website (http://mybackpack.wta.org/), whereas the login in the existing SF template points to staging (http://staging.wta.org/login). Which should we have?

2. The Manage Your Party has a bad link (http://staging.wta.org:6543/login) -- should I change it?

Thanks!
 Drew

**Comment by davisagli** [comment]
@drewpiston mybackpack.wta.org is not the real website, it's a dev/testing site for this project only whereas staging is for testing things that are almost ready to go live. Any URLs for Plone that are generated in Salesforce should be using a custom setting for the base URL so we can change it easily when we deploy to production. We already have a setting like this in VMS_Settings__c for the pyramid app (VMS_Base_URL__c) but not for Plone (there is Plone_API_URL__c but that includes a path for the API).

Manage Your Party should probably go to the work party's VMS_URL__c + '#social' (the url fragment will make it go directly to the Crew Corner tab)

**Comment by drewpiston** [comment]
Thanks @davisagli .

@WaBirder57 This is ready for testing -- some notes:
1. I switched over to process builder (rather than workflow) for this -- was worried that workflow rules were getting to be too numerous. Happy to talk about that more.
2. Right now, if a Work Party Type doesn't have a value in the Email Template Registration field, no email will be sent. If you like I can add an action to the Process Builder that sends out the "general" template if that field is null.

**Comment by mscholtz** [comment]
Thanks, @drewpiston!  Two little things

1) Charlie is on vacation for the entire month of Nov.  So we should be dealing w/ Elliot in his absence, including assigning tickets like this for review

2) Looks like there are a few WF Email Alerts still in there for this, I assume from your initial prototyping using WF.  Could you make sure all that's cleaned up?  (I only noticed b/c I was catching up on git commits and noticed it in there.)  

Thank you!

**Comment by mscholtz** [comment]
@ebskopin overto you for review.  See drew's comment above

**Comment by drewpiston** [comment]
Hi @mscholtz ,

1) Thanks, will do.

2) PB Flows use WF Email alerts, so those need to stay in.

 Drew

**Comment by mscholtz** [comment]
Ah, right, forgot.  Hmm, wish there was a way to see that from the Email Alert.  Maybe put "(sent via PB)" in the label?

**Comment by drewpiston** [comment]
Done!

**Comment by drewpiston** [comment]
I'm going to assign this back to me, as more templates were added since I completed this.

**Comment by drewpiston** [comment]
OK, all of the registration emails should be up to date. A couple of notes:

1. Note that in order to send out an email, an email template must be selected on the Work Party Type record ("Email Registration Template").

2. I modified the Weekend Work Party template slightly -- I added the End Date/End Time and the Days Registered For field. I'll run these changes by Julie.

Cheers,
 Drew

**Comment by ebskopin** [comment]
Thanks Drew.  That looks excellent. I'm assigning the templates now.

**Comment by ebskopin** [comment]
Done.
