### ISSUE TITLE
VMS Info Tab Work Party Header locations should be "region" - "sub region"

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#212]
As illustrated in the prototype design: http://07.wta.emptycan.com/volunteer/details/volunteer-vacation/, the work party header for location should include the Hiking Guide Region and Sub Region for the Work party primary trail segment.   Currently it looks like this is the name of the trail which is often in the name of the work party.  Having the Region and Sub Region displayed will give the reader a better idea about the geographic location of the work party.

The attached screen shot shows the location of the Region and SubRegions on the Hiking Guide Edit page.
![hikingguideregions](https://cloud.githubusercontent.com/assets/8312206/9125722/5090c150-3c58-11e5-81d1-2d07521a9b70.JPG)

**Comment by davisagli** [comment]
We're currently showing the name of the trailhead if the work party has one, otherwise the name of the primary trail segment. I agree showing the region & sub-region would probably be more useful.

If the work party doesn't have a primary trail segment entered or the primary trail segment doesn't have a region/subregion entered, I assume it's okay to not show a location?

**Comment by WaBirder57** [comment]
Yes, I think in the case of the WP not having a primary trail segment or trail head then don't show anything.  Having these assigned is really critical for our reporting purposes so it will be a "flag" to staff that these need to be assigned.

**Comment by davisagli** [comment]
This change is in place now.

**Comment by WaBirder57** [comment]
Looks good, thank you.
