### ISSUE TITLE
WP Registration Changes (delete) doesn't update on Pyramid

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#219]
While this is not a standard user behavior it still seems odd to me.  Basically when a SF Contact Registration record is deleted from a SF Work Party.  In VMS that person still shows as registered for that Work Party.  Seems like once that registration record is deleted from SF that VMS wouldn't still show that registration.  Here is a screen shot from VMS showing the registration is still showing up for that user.

![image](https://cloud.githubusercontent.com/assets/8312206/9279971/fc1843d2-426f-11e5-88af-d894df7deaf9.jpeg)

Here are the details:

User:
sarah.weddington@yahoo.com
password: sarahwta2192

Labor Day Work party: https://cs9.salesforce.com/a2eK0000000wb9t?srPos=0&srKp=a2e  (Note: sarah.weddington registration has been deleted)

**Comment by davisagli** [comment]
Currently a user's registration status for all their work parties is fetched from Salesforce when they log in, and not updated from Salesforce after that until the next time they log in (though it is updated with changes that the user makes via the Pyramid app).  This has the potential to not work well if users can stay logged in for a long time while staff are making changes to their registrations in Salesforce.

Possible solutions:
- Add a timeout to the registration info cached when the user logs in, so that it gets fetched again after some period of time. This is pretty easy, but there's still a delay until Pyramid shows the updates.
- Make Salesforce notify the pyramid app whenever a registration is edited or removed, so that pyramid can update its data at that point. This takes significant effort.

**Comment by WaBirder57** [comment]
Lets go with your first option to add a time out to the registration info cached.  I don't think SF Registration records will be deleted that often so I don't think the 2nd option is necessary.

**Comment by davisagli** [comment]
The pyramid app will now only cache a user's registration info for 10 minutes before it re-fetches it from Salesforce.

**Comment by ebskopin** [comment]
works
