### ISSUE TITLE
MVS Story #291 - Detect Youth via Birthdate

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#225]
If the system determines that the Volunteer is a Youth from the Contact Birthday value then this Youth Check box should appear as "checked".  It should not disappear as in the current implementation.

**Comment by davisagli** [comment]
Chris and I talked about this last iteration; we didn't see the point in giving the user the ability to mark that they are not a youth if we already know from their birthday that they are.

**Comment by chrisrossi** [comment]
We brought it up at a meeting as well, although I can't remember who all
was on that call.

Chris

**Comment by WaBirder57** [comment]
We just want to show that they are in our records as a Youth (under 18).  if that is incorrect they would call the office.  Also a reminder that they need a current parental release form.

**Comment by davisagli** [comment]
So show it, but without the ability to uncheck it?

**Comment by WaBirder57** [comment]
Yes.

**Comment by chrisrossi** [comment]
I've fixed this here: https://github.com/washingtontrails/vms/pull/226

I was a little concerned that merely disabling the checkbox would be confusing to users, so I also added a message in lieu of the birthdate widget: "Your birthdate is registered with My Backpack"  

I'm happy to tweak that language if you like.

**Comment by WaBirder57** [comment]
I like the message now, but this is always displaying.  For example as an sign up for a work party.  This Check Box for under 18 is visible.  However the text "Your birthdate is registered with My Backpack" still displays.  let me know if you need more details about if the user has a birthday and if that check box is in fact checkable.

**Comment by chrisrossi** [comment]
Hi Charles,

The expected behavior is:

1) If you are not logged in or are logged in but the system doesn't know
your birthdate, you see an operable checkbox for 'Under 18' and no
message.  If you check 'Under 18' the birthdate date picker widget appears,

2) If you are logged in, the system knows your birthdate, and you are under
18, you will see an inoperable checkbox for 'Under 18' which is checked,
along with the message stating that we already know your birthdate.

3) If you are logged in, the system knows your birthdate, and you are 18 or
older, you will see an inoperable checkbox for 'Under 18' which is not
checked, along with the message stating that we already know your birthdate.

I've tested again on my end, and it seems to be behaving as expected.  Does
this run counter to your expectation?

Chris

**Comment by WaBirder57** [comment]
OK this works, thanks.
