### ISSUE TITLE
Story #259 Site header Plone

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#228]
This Plone header is not the same on Pyramid as Plone.  When Logged into Plone (mybackpack.wta.org) the header shows the image from the users profile. When logged into pyramid the header doesn't show this image or indicate the identity of the person logged in.  Attached are screen shots of these two different headers.
![pyramidloggedinheader](https://cloud.githubusercontent.com/assets/8312206/9507726/f9b339dc-4c04-11e5-94d5-13108e134f93.JPG)
![ploneloggedinheader](https://cloud.githubusercontent.com/assets/8312206/9507727/f9b5adf2-4c04-11e5-9a10-60c7cc0b4010.JPG)

**Comment by davisagli** [comment]
Oh right, I set up the one in Pyramid before the design was finalized and need to adjust it. Thanks for the reminder.

**Comment by cewing** [comment]
I'll take this one on.

**Comment by cewing** [comment]
@WaBirder57, @davisagli: just for the sake of clarity here.  Is the idea to make the VMS header work **exactly** like the header in Plone?  There are a few things going on there that need work:

1.  When logged in, the 'my backpack' bit is blue, but when not, it is orange.
2.  When logged in, the icon shown in the my backpack bit is the user portrait, if the user has one, otherwise it's the circular hiker logo on a light grey background
3.  When anonymous, the icon shown is just the hiker in white with no terrain or circle around it.
4.  At tablet sizes, the My Backpack thing moves to the side of the hamburger menu where site navigation goes, the scale of the hiker image changes, and the background is blue for both authenticated and anonymous users.

Of these, the only ones that currently work are 3 and 4.

**Comment by davisagli** [comment]
Right, we should fix 1 and 2. The design for the My Backpack button wasn't finalized when I worked on this before.

**Comment by davisagli** [comment]
should work correctly now
