### ISSUE TITLE
Vol Vacation Payments create extra (duplicate) contact

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#231]
When a person, non member,  makes a payment for a Vol Vacation (or other WP with payment) the Zero dollar Membership Opportunity is created for this contact.  Then a New Contact is created with the actually Fee payment opportunity.  All these Opportunities should be on the same SF Contact, the one with the WP registration.  

It seems this is also the case for a Member who pays for a WP.  The opportunity created is linked to a whole new contact record, not the contact record of the person registering for the WP.

**Comment by davisagli** [comment]
@mscholtz how does CnP match contacts?

**Comment by mscholtz** [comment]
@drewpiston how well do you know Click & Pledge.  Do you feel comfy trying to troubleshoot this one?  If not, I can tackle it next week.

**Comment by WaBirder57** [comment]
In our production salesforce if you go to the C&P app.  Click on the C&P
Settings tab.  On the left hand vertical menu click on Accounts and
Contacts.

There you can see the settings to Match Contacts.  Here is a screen shot
(which may not come through).  Also this is may not be sefl explanatory,
kara@wta.org or aaron@wta.org might also be able to help explain this.  I'm
back next week.

Charlie

[image: Inline image 1]

Charlie Kahle
Information Services Manager
Washington Trails Association
705 Second Ave, Suite 300
Seattle, Wa 98104
206.625.1367 - office
206.388.4511 - direct
www.wta.org

**Comment by mscholtz** [comment]
This should be fixed now.  It was not using the right email fields on the SF side to match existing contacts.

One possible issue though, @WaBirder57 : in production, your C&P Settings are set to match on mailing address, in addition to name and email.  Our understanding of that is that if it doesn't match on all 3 of those things, it'll create a Temp Contact.  And that would be a big problem, since 

a) they only have 5 minutes to complete the payment, and 
b) C&P doesn't create an opp until the temp contact is resolved, and 
c) our code doesn't mark them paid until the opp is created, and
d) the contact in SF may or may not already have a street address when the payment is made 

Do you need it to be matching on Street in production?  None of our other clients do that, since it produces a lot of false negatives.  If we could remove that matching criteria we'd be much less likely to run into this.

Assigning to you @WaBirder57 for now, to weigh in on that.

**Comment by WaBirder57** [comment]
We have discussed this and we do use the Temp contacts created when the billing address doesn't match a mailing address to verify if that is a change we want to make.  Reasons why there may be a difference include seasonal address as well as folks who get their magazines and other mail at a different address (eg Europe) from their CC billing address.

In order not to hold up the Vol Vac payment completion is it possible to use payment confirmation from the C&P response codes (http://manual.clickandpledge.com/Response.html) to verify that a payment was made successfully (as well as flag if it was not accepted).  Then run the Salesforce Opportunity completion asynchronously.  

Alternatively using the C&P transaction data which include payment status (transaction result) and is created regardless of the status of the associated Opportunity could be a quick way to update the VMS payment registration status

**Comment by mscholtz** [comment]
Yes, either of those might be possible.  But would be a new story, which I'm not sure we have enough time for.  But please go ahead and put it in if you'd like us to try.

I'm going to mark this ticket reviewing, please close it if you agree that the duplicate contact creation has been resolved.

**Comment by mscholtz** [comment]
Not sure if we can use the response code, because as I understand it, VMS is simply submitting the form directly to C&P, rather than using their API.  So not sure if it's getting a response code.  @davisagli can you weigh in there?  Are you getting a response code from C&P that you could pass to SF?

**Comment by davisagli** [comment]
Pyramid does get a response from C&P (we submit to a hidden iframe and pass a callback URL that C&P redirects to). I'd have a couple concerns about using it though:
1. If the user's browser closes or crashes after the payment is sent to C&P but before the callback is received, the payment wouldn't get recorded.
2. We'd have to be sure to validate that the callback was called by C&P. It looks like it has a way to configure a secret so that you can verify a hash included in the callback, so this should be possible.

**Comment by WaBirder57** [comment]
I would like to address this issue of the Paid work party registration not being marked complete (paid) if C&P creates a temporary contact and delays the opportunity record from being created.  If we receive payment (see response code) that is sufficient to handle these quickly.  We can clean manually match contacts and have the opportunity creation later.  We expect some 300 paid registrations happening the morning we first launch Volunteer Vacations so we need an efficient we to quickly accept payments and registrations.

Do we need a new ticket for this, new story?  @kuffelman if we need to pay you more to make this happen let me know what it will take.

**Comment by WaBirder57** [comment]
The issue of the duplicate contact being created on Vol Val payment has been fixed.  Thank you.

**Comment by mscholtz** [comment]
@WaBirder57 I think write a story for it, put it near the top of the backlog.  We can figure out on Monday which approach to take, and if everything you need looks like it'll fit into the iteration or not.

**Comment by ebskopin** [comment]
Do we still need a story for this?

*Elliott Skopin*
Volunteer Program Coordinator
Washington Trails Association
wta.org <http://www.wta.org/> l Facebook
<https://www.facebook.com/washingtontrails>
(D) 206-557-3406
(O) 206-625-1367

Help WTA celebrate 20 years of trail maintenance - Join a work party!
<http://www.wta.org/volunteer/trail-work-parties>
