### ISSUE TITLE
WP Finder List - Time is different than the WP Info tab - Time

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#234]
When looking at a work party in the WP Finder list the time may be shown as 8:30am - 3:30pm.  When you click to open a WP the time on the Info tab is shifted 7hrs to be 3:30pm - 10:30pm.

The time on the detailed WP Info should show the same time as the WP is scheduled for and be the same as shown on the WP Finder view.

**Comment by cewing** [comment]
@WaBirder57, there is a decision that needs making here.  If you want to skip the long description, the choice is between forcing all time displays to be local to WA state and allowing them to be local to the user's browser (if I'm in Colorado, the time displayed will be 1 hour later than it is here).

What follows is a longer description of the cause, the solutions available and the outcomes.

The cause of this issue is that when the workparty is being displayed in the list view on the search page, the javascript that renders that page is automatically converting the date to the local time zone of the user's browser.  In the view of a single workparty, the time is being rendered with the actual value stored in the index (which is in UTC, or [coordinated universal time](https://en.wikipedia.org/wiki/Coordinated_Universal_Time)).  

We have two options here:

1.  We pre-convert all times from the stored UTC to Pacific Time when we draw information out of the search index, and then render those values un-converted into the page (this means preventing our javascript from trying to do the conversion on its own).  

2.  We ensure that every place where we render a date-time we do so using the javascript we have which would ensure that in all cases the same values would be displayed to users (and these values would always be local time for the viewer of the page, as reported by their computer).

The only substantive difference from a user's perspective between these two is that in the case of option 1, the displayed time can be ensured to always be Pacific Time whereas in option 2 the time displayed would always be the time in whatever timezone the viewer is located.  In terms of implementation difficulty, either is approximately equal in complexity.

Could you please indicate which of these two options you prefer?

**Comment by cewing** [comment]
personal note: see Javascript `utils.DateRange` for the javascript function that is rendering date ranges

if option 1 is chosen, create a python utility that can convert datetime values to appropriate local times and then send those values to js without any TZ offset values to prevent moment.js from automatically converting them to browser local time.

**Comment by cewing** [comment]
@WaBirder57: actually, reading #233, it would appear that you want time always to display in WA state local time, not in the user's timezone.  If that is true, then the above question need not be answered, and I will pursue option 1

**Comment by WaBirder57** [comment]
Elliott and Rebecca,

My understanding is that the Work party times should always display in
local Seattle time no matter where in the world the user is located.  Thus
option #1 below

Please reply all to this email so Chris knows how to build this.

Thanks.

Charlie

Charles Kahle
WTA Information Services Manager

**Comment by WaBirder57** [comment]
Yes, Charlie, it should always display Seattle time no matter where the
user is.

On Tue, Sep 8, 2015 at 9:25 AM, Charlie Kahle <charles@wta.org> wrote:

> Elliott and Rebecca,
>
> My understanding is that the Work party times should always display in
> local Seattle time no matter where in the world the user is located.  Thus
> option #1 below
>
> Please reply all to this email so Chris knows how to build this.
>
> Thanks.
>
> Charlie
>
> Charles Kahle
> WTA Information Services Manager
> On Sep 4, 2015 5:16 PM, "Cris Ewing" <notifications@github.com> wrote:
>
>> @WaBirder57 <https://github.com/WaBirder57>, there is a decision that
>> needs making here. If you want to skip the long description, the choice is
>> between forcing all time displays to be local to WA state and allowing them
>> to be local to the user's browser (if I'm in Colorado, the time displayed
>> will be 1 hour later than it is here).
>>
>> What follows is a longer description of the cause, the solutions
>> available and the outcomes.
>>
>> The cause of this issue is that when the workparty is being displayed in
>> the list view on the search page, the javascript that renders that page is
>> automatically converting the date to the local time zone of the user's
>> browser. In the view of a single workparty, the time is being rendered with
>> the actual value stored in the index (which is in UTC, or coordinated
>> universal time <https://en.wikipedia.org/wiki/Coordinated_Universal_Time>).
>>
>>
>> We have two options here:
>>
>>    1.
>>
>>    We pre-convert all times from the stored UTC to Pacific Time when we
>>    draw information out of the search index, and then render those values
>>    un-converted into the page (this means preventing our javascript from
>>    trying to do the conversion on its own).
>>    2.
>>
>>    We ensure that every place where we render a date-time we do so using
>>    the javascript we have which would ensure that in all cases the same values
>>    would be displayed to users (and these values would always be local time
>>    for the viewer of the page, as reported by their computer).
>>
>> The only substantive difference from a user's perspective between these
>> two is that in the case of option 1, the displayed time can be ensured to
>> always be Pacific Time whereas in option 2 the time displayed would always
>> be the time in whatever timezone the viewer is located. In terms of
>> implementation difficulty, either is approximately equal in complexity.
>>
>> Could you please indicate which of these two options you prefer?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/washingtontrails/vms/issues/234#issuecomment-137876621>
>> .
>>
>


-- 
Rebecca Lavigne | Trail Program Director
Washington Trails Association
705 Second Ave Suite 300
Seattle WA 98104

206.625.1367 - office
206.965.8559 - direct
www.wta.org

**Comment by cewing** [comment]
All set, then.  Thanks.  I've got a PR open to solve this and #233.

**Comment by davisagli** [comment]
This should now work correctly.
