### ISSUE TITLE
Story #250 - Email notice doesn't list friends and family members.

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#240]
This did not work for me. In VMS, as Soren Eagle, I signed up with Li Chen and Al Pine, and my confirmation email says party of 1, and their names are not included. This is for a "day work party." Is the confirmation email template for this work party type just not correct? It was this work party: https://cs9.salesforce.com/a2eK0000003Oyat (JC 9/1)

**Comment by mscholtz** [comment]
@drewpiston could you start with this ticket?  I've also got a story for you (162) but need to verify something w/ Charlie on that.

**Comment by drewpiston** [comment]
Hi @WaBirder57 ,

Could you send me the email you got?  I'm looking at Soren Eagle's record (great name) and it looks correct. Did you get the email at jacassata@gmail.com?

Thanks,
 Drew

**Comment by drewpiston** [comment]
Hi @mscholtz ,

This was broken because I neglected to delay the email by 5 minutes so that the custom roll-up had time to work.

However, I think I have a solution that doesn't rely on the email delay -- would you be willing to look at WTA_VMS_REST_CreateRegistration and let me know if you think it's not too convoluted? I don't like delaying the email, and we have all of the info in that method so I think this makes sense.

Relevant lines:
WTA_VMS_REST_CreateRegistration.cls 190, 198-199, 214-222
WTA_VMS_WP_Registration_TriggerClass.writeFamilyAndFriendsInfoToHeadOfParty method

Thanks!
 Drew

**Comment by drewpiston** [comment]
Matthew approved code, I added comments, and this is ready for review!

**Comment by WaBirder57** [comment]
Good.
