### ISSUE TITLE
Missing fields for work party on Salesforce.

### ISSUE THREAD

**Issue by cguardia** [washingtontrails/vms#244]
Turns out the description field can be longer than what is shown on the iteration page in ScrumDo, so we missed some fields that need to be added. This ticket is for adding them to Salesforce.

- Before/After WP Location - Header 2, move this to the Location Tab so directions to the WP as well as any Before/After event are display and printed together.

- Work Party Schedule - Header 2

- Planning information  - Header 1

- What it takes to do this work party - Header 2

- What to Wear - Header 2

- What to Bring - Header 2

- More Info - Header 1, note links to FAQ, Trail Work Guide webpages.  Also link to Hiking Guide and Trip Reports about this area (this is based on the Hiking Guide URL for the work party).

**Comment by mscholtz** [comment]
@cguardia I created all of these fields.  Some changes to "What to Bring" are waiting on a question for Charlie, but the field exists.  It's just plain text instead of rich at this point.

New Fieldnames:

* Before_After_Party_Location__c
* Work_Party_Schedule__c
* Planning_Information__c
* What_It_Takes__c
* What_to_Wear__c
* What_to_Bring__c
* More_Info__c

BTW, it's not clear to me how More Info is different from Additional Information.  Just asked Charlie that in the comments of the story, or we can ask at standup.
