### ISSUE TITLE
fix 'cancel registration' link from My Work Parties

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#251]
My Work Parties shows a 'cancel registration' button for upcoming work parties which links to VMS, but it doesn't work because it's a POST-only endpoint that is meant to be called via AJAX. We need to fix this.

**Comment by cewing** [comment]
This is fixed and will be ready for review once the PRs are merged and released.

**Comment by cewing** [comment]
@WaBirder57: the fix for this has now been deployed to the testing site.  You should be able to see it in action.

### To Test
* Ensure that you are **not** logged in to http://staging.wta.org:6543/
* Go to mybackback.wta.org and log in as a user with one or more upcoming work parties
* Click on "cancel" for one of the work parties.
* Verify that when the page reloads, that work party is no longer in your list of upcoming.

You can also verify that the same functionality works when you *are* logged in to VMS.

**Comment by WaBirder57** [comment]
Works like a charm, thanks.
