### ISSUE TITLE
Confirmation email sent too early for paid registrations

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#271]
I started to register for http://staging.wta.org:6543/workparty/a2eK0000002OXWL/ which has fees.

I received a confirmation email soon after I reached the payment form, without submitting the payment form.

Seems like we should not send the confirmation until payment is received. Not sure if the bug is that Salesforce is marking the registration as Registered too soon, or that the confirmation email is getting triggered for a status of Payment Pending.

**Comment by davisagli** [comment]
The registration in SF has a status of Payment Pending, so it seems like the latter.

**Comment by davisagli** [comment]
I'm confused why this happened, because the workflow is only triggered with status = 'Registered' -- https://cs9.salesforce.com/01QK00000001GEy

Does the registration get created first with a status of Registered and then get transitioned to Payment Pending after that, or something?

**Comment by davisagli** [comment]
My registration is https://cs9.salesforce.com/a2oK0000000mnPi

**Comment by mscholtz** [comment]
Yes, the issue here is in the interaction between the webservice and the trigger that checks capacity and puts people on the waitlist.  

The way this currently works is:

* webservice inserts reg w/ empty status
* before insert trigger fires, checks if there's space, then assigns either Registered or Waitlisted
* webservice then switches it to Payment Pending if it's not Waitlisted and the WP requires a fee

End result: Reg is in status Registered for a moment

So we need to re-engineer how this works.  Here's the easiest solution I see:

* webservice checks before insert if payment is required, and attempts to set either Payment Pending or Registered on insert
* change trigger to not expect a blank status on insert - instead if incoming status is Reg or PP, it will still check capacity.  If no capacity, status becomes Waitlisted.  if capacity exists, keep the incoming status
* no change needed to how trigger handles updates

**Comment by mscholtz** [comment]
Hi @ninetaLogik think you could tackle this one as well?  Let me know if you have questions, but see my last comment.

**Comment by ninetaLogik** [comment]
@davisagli  This should be addressed now. Assigning back to you since you filed it.

**Comment by davisagli** [comment]
It works now; thanks.
