### ISSUE TITLE
What Vol Vac payment form is completed, volunteers

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#275]
When a volunteer registering for a Volunteer Vacation (http://staging.wta.org:6543/workparty/a2eK00000000iUN/) completes the Payment page they get the following (attached) registration confirmation page which indicates that the payment is pending.
![registration status payment pending](https://cloud.githubusercontent.com/assets/8312206/10199345/1b8820de-6755-11e5-8240-0ed85ddbd4e8.JPG)

Is this to be expected? (or should this show status of "registered"?)

What happens of the CC payment is denied or fails?

**Comment by davisagli** [comment]
It shows Payment Pending because the update of the registration status in Salesforce is asynchronous: C&P authorizes the payment and lets pyramid know it was authorized, then C&P separately records the opportunity in Salesforce (which triggers the update of the registration status).

If payment fails then C&P notifies the pyramid app of that and it shows an error. You can and should test this by entering a bogus credit card.

I think it should be safe to show 'Registered' here (the registration was already created with a status of Payment Pending which reserves a spot in the work party, and we have confirmation from C&P that payment was authorized) and that would be a pretty easy fix.

**Comment by davisagli** [comment]
This should now show Registered if the payment was successfully processed.
