### ISSUE TITLE
#12 WP show all public info to guests - where are the Landmanger Logo's stored

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#28]
The Land Managers at the bottom of the WP info tab correctly pick up the name of the land manger(s) associated with all the trail segments for that work party.  The corresponding logo's are not.  Where are these stored in Salesforce?  These need to show on the WP Info Tab along with the name of the land manager.

**Comment by davisagli** [comment]
This isn't implemented yet; it's just showing a hardcoded placeholder logo. Is it okay if we add a Logo URL field to Accounts in Salesforce so you can upload a logo in Plone and then paste the URL in Salesforce, like we currently have set up for images?

**Comment by WaBirder57** [comment]
Yes that will work for now.  Does plone/pyramid handle image sizing or do we need to make sure the images on the web are the size we need for the web display?

**Comment by davisagli** [comment]
If you've got an image in Plone, Plone can generate scaled versions of the image with a modified URL. For example here's a full-size image:
http://www.wta.org/hiking-info/gallery/images/2015/snowdrifts-and-shuksan
here's a mid-size version of it:
http://www.wta.org/hiking-info/gallery/images/2015/snowdrifts-and-shuksan/@@images/image/preview
and here is a thumbnail:
http://www.wta.org/hiking-info/gallery/images/2015/snowdrifts-and-shuksan/@@images/image/thumb

We could either make you be responsible for choosing the right URL, or we could have you enter the full-size image URL and then VMS could automatically tack on the suffix for the scale it wants to use in a particular place. Got a preference?

(VMS will always tell your browser to constrain the image when it's displayed so that it fits in the design regardless of the actual file size...but if it's downloading the fullsize image just to display a thumbnail, that's inefficient.)

**Comment by davisagli** [comment]
@mscholtz assigning this to you so you can have someone on your team add that Logo URL field to Account.

**Comment by davisagli** [comment]
This is now story 171.
