### ISSUE TITLE
MBP Trip Report submission Error

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#285]
When user charlesfkahle@kahle.org tries to submit a trip report I get the followiing error.  This may be related to difficulties selecting the hike this trip report is for.

![mbptripreportsubmissionerror](https://cloud.githubusercontent.com/assets/8312206/10288527/430fdae6-6b4e-11e5-9eb1-3fbeca5ae554.JPG)

**Comment by davisagli** [comment]
Traceback:

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module z3c.form.form, line 215, in __call__
  Module wta.content.browser.forms, line 714, in update
  Module z3c.form.form, line 210, in update
  Module z3c.form.action, line 99, in execute
  Module z3c.form.button, line 315, in __call__
  Module z3c.form.button, line 170, in __call__
  Module wta.content.browser.forms, line 759, in save
  Module wta.content.browser.forms, line 786, in _handleSave
  Module wta.content.browser.forms, line 806, in _bootstrapTripReport
  Module wta.content.content.utils, line 16, in getTripReportsBucket
  Module OFS.Traversable, line 317, in restrictedTraverse
  Module OFS.Traversable, line 285, in unrestrictedTraverse
   - __traceback_info__: ([], 'trip-reports')
AttributeError: trip-reports
```

**Comment by alecpm** [comment]
For some strange reason someone moved/renamed the trip-reports folder to "Trip Reports".  The intent was probably to change the title, but the id/short-name was changed instead, causing existing links to create trip reports to fail.  The undo history is as follows:

/wtamain/wtaadmin/go-hiking/folder_moveitem by wtamain/wtaadmin kindra@wta.org
2015-09-29 08:06:45

/wtamain/wtaadmin/go-hiking/folder_rename_form
Renamed ['/wtamain/wtaadmin/go-hiking/trip-reports'] by wtamain/wtaadmin kindra@wta.org

I've renamed and titled it correctly, and this should be fixed.

**Comment by WaBirder57** [comment]
This is happening again (10-6-2015 at 6pm).  When i try to submit a trip report I get the following error.

![mbptripreportsubmissionerror-2](https://cloud.githubusercontent.com/assets/8312206/10326798/3455e7b4-6c54-11e5-8842-d8f72ce828dd.JPG)

**Comment by alecpm** [comment]
The traceback below indicates that you entered "15" which it took to mean 15 AD instead of 2015 and didn't like that date:

Time
Oct 06, 2015 05:58 PM
User Name
charlesfkahle@kahle.org (charlesfkahle@kahle.org)
Request URL
https://mybackpack.wta.org/go-hiking/hikes/hike-with-1-supplement/@@tripreport-add
Exception Type
ValueError
Exception Value
year=15 is before 1900; the datetime strftime() methods require year >= 1900
Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module z3c.form.form, line 215, in __call__
Module wta.content.browser.forms, line 879, in update
Module wta.content.browser.forms, line 714, in update
Module z3c.form.form, line 210, in update
Module z3c.form.action, line 99, in execute
Module z3c.form.button, line 315, in __call__
Module z3c.form.button, line 170, in __call__
Module wta.content.browser.forms, line 759, in save
Module wta.content.browser.forms, line 788, in _handleSave
Module wta.content.browser.forms, line 778, in _applyDataToAdaptedTripReport
Module wta.content.browser.forms, line 422, in _setTripDate
Module wta.content.browser.forms, line 379, in dt2DT
ValueError: year=15 is before 1900; the datetime strftime() methods require year >= 1900

**Comment by alecpm** [comment]
This should be easy to fix, since it's in appears to be in our custom setter.  It might also make sense to fill in a default date (today) there.

**Comment by WaBirder57** [comment]
Yes, it would be great to fix as well as add the default (today) as a
starting point.

Charlie Kahle
Information Services Manager
Washington Trails Association
705 Second Ave, Suite 300
Seattle, Wa 98104
206.625.1367 - office
206.388.4511 - direct
www.wta.org

**Comment by davisagli** [comment]
It now defaults to today's date, and will show a more helpful validation error if the user enters a year before 1900.

**Comment by WaBirder57** [comment]
Yes , that is much better.
