### ISSUE TITLE
Salesforce Rich Text Area field provides too much space after ordered list elements

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#308]
The Salesforce Rich Text Area field that we use for the WP description fields, such as Planning Information display in VMS with to much white space after an Ordered (numbered list) or Unordered list (bullets).  Is there a way to change this style so that there is not so much empty space on the WP Info tab?  We would like no extra space after these formatting elements.

The Thanksgiving Day work party (2016) is an example: https://cs9.salesforce.com/a2eK00000000iVz which is displayed here: http://staging.wta.org:6543/workparty/a2eK00000000iVz/

**Comment by davisagli** [comment]
The space actually isn't due to the lists; it's space that was in the template in between sections. I just removed it. Better?

**Comment by WaBirder57** [comment]
Yes, looks much better thanks.

**Comment by WaBirder57** [comment]
Charlie,

David are we/you able to address some of the formating suggestions that Rebecca has on this VMS Info Tab.  Check out the WP in the link below for a good example - Charlie

Progress! The spacing around bulleted lists is much better. However, this appears to have eliminated the (prefered) spacing after normal paragraphs so that the subheaders are crammed underneath. The font sizes still don't match - the font for the bulleted lists is larger than the body text. I much prefer the font size being used for the bulleted list. I think the other size is pretty small.

You see see how this plays out here: http://staging.wta.org:6543/workparty/a2eK0000002OXU0/

-Rebecca

**Comment by davisagli** [comment]
I think the problem is that some of the fields coming from Salesforce do not have paragraph tags (i.e <p>) around their text, and the formatting only works correctly for paragraphs.

If it's not easy to coax Salesforce to add paragraph tags, I can make the pyramid app wrap the field values with them when they aren't already there. Should I do that?

**Comment by WaBirder57** [comment]
Yes if you could do it only if needed that would be great.  Other than changing the field type in SF I wouldn’t know how to do this.

 

Charlie

**Comment by cguardia** [comment]
@davisagli Added a fix for this.

**Comment by davisagli** [comment]
@cguardia you did exactly what I said but we actually need to do more because there are some field values that contain a valid paragraph or header followed by some text that is not wrapped with any tag. For example the Overview field for this work party: http://staging.wta.org:6543/workparty/a2eK00000000gHB/

Can you change it so that it splits the field on \n\n, and uses your logic to add p tags around all of those sections that aren't already wrapped in a tag, then joins them back together?

**Comment by davisagli** [comment]
This is already quite a bit better though, @WaBirder57

**Comment by cguardia** [comment]
@davisagli ok, I think I got it now.

**Comment by davisagli** [comment]
Looks good to me.

**Comment by WaBirder57** [comment]
Good.
