### ISSUE TITLE
MBP: Trip Report List view in My Backpack Trip Report Section: Sort by votes not working

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#311]
When a logged in user looks into their own My Backpack Trip reports.  Select "Most to Least Up Votes" (for the sort order).  No Trip reports are returned.  The other options, Chronological and Alphabetical, work as expected.

**Comment by davisagli** [comment]
@cewing could you please take a look at this one?

**Comment by cewing** [comment]
It would appear that the problem here is that the interface that supports indexing for twothumbs is not provided by the trip report content type.  I'll fix that and it should allow this to work.  As an aside, this should also mean that the display of the maximum number of upvotes on the trip reports page (and on the my backpack dashboard in the trip reports widget) will work properly too.  I don't expect that those are working correctly either, at this point.

**Comment by davisagli** [comment]
Should work now. Thanks for the diagnosis and fix @cewing.

**Comment by WaBirder57** [comment]
It works, thanks!
