### ISSUE TITLE
VMS: Create new work party fails on Appex Trigger when CL is assigned

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#318]
When creating a new work party, select a Crew Leader and Save.  You get the following error:

Error: Invalid Data.
Review all error messages below to correct your data.
Apex trigger WTA_VMS_Work_Party_After caused an unexpected exception, contact your administrator: WTA_VMS_Work_Party_After: execution of AfterUpdate caused by: System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, You must select a status for the work party registration.: [Status__c]: Class.WTA_VMS_WP_Manage_CLRegistration.manageCLWorkPartyRegistrations: line 45, column 1

Here is a screen shot:
![createwleadererror](https://cloud.githubusercontent.com/assets/8312206/10489228/fb7878be-7250-11e5-8025-c77371d3ba1a.png)

**Comment by mscholtz** [comment]
@WaBirder57 I'm going to look into this now.  I will try to fix it but I have a doctor appointment this afternoon and may not be able to do so before that.  If that's the case I can do it later today or tomorrow.

BTW, for urgent issues like this it would be very helpful if you could @ mention me, or assign the ticket to me.  Otherwise I don't get any notification.  I only heard about this b/c David happened to spot it.

**Comment by mscholtz** [comment]
@WaBirder57 in the meantime you can use this workaround:

* initially create a WP without a leader
* add a registration for the leader w/ role = Leader and Status = Registered

that will automatically update the leader field on the WP

**Comment by mscholtz** [comment]
note to self: failing test exposes this in WTA_VMS_TEST_WP_Manage_CLRegistration.cls

**Comment by WaBirder57** [comment]
@mscholtz Thanks for the work around and trying to get to this ASAP.

**Comment by mscholtz** [comment]
this is fixed

**Comment by WaBirder57** [comment]
It works, thanks.
