### ISSUE TITLE
canceling registration does not work

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#341]
If I click the Cancel Registration button in VMS, it changes to Cancelling... and just sits there.

This used to update the registration info in the session which triggered a rerender, but now registration info is no longer in the session so we need to update it a different way.

**Comment by WaBirder57** [comment]
Is this also affecting the VMS Crew Corner tab.  When i click on "Cancel" for a registered participant it flashes for a sec (looks like is says Submitting) and then goes back to "Cancel". Nothing happens to the registration record in Salesforce, the registration status does not change.  If this is a different issue we can move my comment to a new Ticket.

**Comment by davisagli** [comment]
Not sure if it's the same, we'll figure that out. Thanks for mentioning it.

**Comment by cewing** [comment]
@davisagli, I've got the cancel button fixed so that the `WorkPartyStatus` component is appropriately redrawn after the AJAX call to cancel the registration returns successfully.  

I'm still working out how we might deal with the fact that we can still see information in the `WorkPartyCrewCorner` component and the `WPReportLoader`/`WPReportView` components, which may now be in the page, but should no longer be.  See comments in https://github.com/washingtontrails/vms/commit/eaa42abe8b547052d1f44331b839001e35982f0c

**Comment by davisagli** [comment]
Both of these scenarios should work now.

**Comment by WaBirder57** [comment]
Seems to be working, thanks.
