### ISSUE TITLE
VMS: Crew Messageboard time-stamp incorrect & Staff title change

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#425]
With the crew message board, when staff post a message, the "signature line" should be:

[Name] - Staff

Right now is says [Name] - Admin which is a very techy way to do this. Not what I think makes sense for WTA.

Also, the time stamp is not correct. I posted a message around 3pm today and the time stamp was 12:00am. If the time won't be accurate then it should show the date only, and not show the time.

Here is a screen shot of this from http://staging.wta.org:6543/workparty/a2eK0000003Oymf/

![image](https://cloud.githubusercontent.com/assets/14843712/11134429/8932726a-8951-11e5-953e-5c3e257a644d.png)

**Comment by davisagli** [comment]
We are only storing the date, not the time that the message was sent. @mscholtz could we change the Date Sent field on Work_Party_Message__c to be a datetime field instead of a date so we can record and display the time the message was sent?

In the meantime I changed it to not show the time.

I also changed it so it'll change Admin to Staff when it generates the message signature. Since the signatures is part of the message text that will only take effect for new messages.

**Comment by mscholtz** [comment]
I could do this, but since our VMS QA period is done, and I'm gearing up to do the deploy, I would like to either
a) skip this and let it just show a date, or
b) do this later (prob. in December, the next QA period for us)

**Comment by ebskopin** [comment]
option a) works just fine as far as I'm concerned.

**Comment by mscholtz** [comment]
OK, great, @ebskopin.  Then just close this ticket if you're satisfied w/ David's changes.

**Comment by ebskopin** [comment]
yep, changes look good.
