### ISSUE TITLE
VMS: Remove Red Confirmation Pop-up when joining waitlist

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#426]
Upon clicking the "Join Waitlist" button at the bottom of the registration page, a red pop-up box appears (http://prntscr.com/8ub33m). This can be removed and, once the "Join Waitlist" button is clicked, the user should be navigated directly to the "Thank-you" page.

**Comment by davisagli** [comment]
Are you sure? We did it this way because there is a chance that the red box is the first indication the user sees that they are joining the waitlist rather than registering -- that could happen if user B took the last spot after user A loaded the registration form (so the button would say Register rather than Join Waitlist).

Also, if the user is registering friends/family and they entered an email address for each person, the red box gives the user a choice of whether to join the waitlist as a group or as individuals (story 254). If we remove this confirmation they won't get that choice.

**Comment by ebskopin** [comment]
Yep, that would make sense.  I'm gonna alter this ticket to reflect some aesthetic changes. Thanks for bringing that to my attention.

**Comment by ebskopin** [comment]
going to retain current design for now
