### ISSUE TITLE
Story #84 - When a volunteer completes a required document, friends docs are also, mistakenly, marked as completed.

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#46]
This worked as intended for me, but I noticed that when I clicked on the registration of the friend I added on the Pyramid side and went to her documents, her medical form also said "done" even though I did not mark her document as completed on her Salesforce record.

**Comment by davisagli** [comment]
The documents tab in pyramid only shows your own documents status (i.e. for the currently logged in user). So I'm not sure what you mean about clicking on your friend's registration and going to her documents; there isn't a way to do that.

**Comment by skleinfeldt** [comment]
@WaBirder57 can you explain this ticket? The document status for other people you registered is not shown in the mockup, it’s not clear how/where it should be shown, and we haven't tried to implement that. Maybe you were confused because the names in the crew list were links that didn’t actually go anywhere? (David has since changed them to go to the person’s my backpack page.)

**Comment by kuffelman** [comment]
What was confusing for me (it was me that reported this issue) is that I signed up another person (my young son), but even though I hadn't filled out a medical history report for him, because mine was completed in my documents section it looks like everything has been submitted. Which it has for me, but not for my party. I understand, now, why it wouldn't (and probably would get an email saying I need to fill out a form for him, yes? since I gave my email address for him), but as a parent signing up my kid, if I missed the email with the reminder for the medical form for him, there would be no indicator that we were missing any required documents if I had already done mine. Not sure we need to change anything, but that's why I thought there was a problem...I was expecting to see two documents required in my documents tab, one for me that was marked complete and one for him that wasn't.

**Comment by kuffelman** [comment]
Actually, it's no longer showing that my medical form is completed, so I can no longer recreate the original issue. I just tried going back into the SF sandbox and submitting a new medical form for me, but it's still not showing up in Pyramid.

**Comment by kuffelman** [comment]
Now that I'm going through this again, I think that previously when I clicked on the family-member-that-I-registered's name, it seemed that I could click on the documents tab for that person and would see the medical form showing as complete.

**Comment by davisagli** [comment]
After pyramid looks up your document status once it's cached for 10 minutes (to avoid using API calls every time a logged-in user loads the page), so try again in a bit. Unfortunately we don't have a good way for Salesforce to notify Pyramid when a completed document is received from formassembly.

**Comment by davisagli** [comment]
> Now that I'm going through this again, I think that previously when I clicked on the family-member-that-I-registered's name, it seemed that I could click on the documents tab for that person and would see the medical form showing as complete.

You thought you were clicking to view that person's registration, but really the link just didn't go anywhere and you were still viewing your own registration. We haven't built a way to view another person's registration.

**Comment by kuffelman** [comment]
That seems right.

**Comment by skleinfeldt** [comment]
So can this ticket be closed?

**Comment by skleinfeldt** [comment]
@kuffelman @WaBirder57 can we close this ticket? Assigning to @WaBirder57 since I don't think there is anything for us to do.
