### ISSUE TITLE
VMS: Group Registration/Management 

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#485]
There are some issues with managing groups. 

1. Presently, as the group organizer, I am unable to remove my participants from the roster in Crew Corner. When clicked, the "Cancel" button briefly flashes "Submitting..." but does not cancel the contact in VMS or Salesforce.

2. The "Add a Crew Member" should include an e-mail field, and ideally would allow the organizer to add more than 1 contact at a time (5 fields could display initially, and 5 more could be added subsequently). 

3. Presently, the "Add a Crew Member" field prompts the following for WP:http://staging.wta.org:6543/workparty/a2eK00000000th7/
https://cs9.salesforce.com/a2eK00000000th7 
![image](https://cloud.githubusercontent.com/assets/14843712/11729895/9426a0aa-9f46-11e5-93bd-c4540e4054d0.png)

**Comment by davisagli** [comment]
1 - We'll take a look.

2 - We chose to only handle one at a time so that we could reuse the same Salesforce webservice that handles non-group registrations. Handling multiple registrations here would have been a significantly larger story.

The email field will show up if you check the "Organizer Must Provide Emails" checkbox on the Work Party Group.

3 - is an error from Salesforce. @mscholtz?

**Comment by ebskopin** [comment]
Thanks. 

I'm still finding that the e-mail field is not present even when the "Organizer Must Provide Emails" is checked.

**Comment by davisagli** [comment]
It's showing up for me on the work party you linked above...maybe you just didn't wait for a minute for the work party index to update after you changed it?

**Comment by ebskopin** [comment]
Huh, I'm still not seeing it. Just to confirm that we're looking in the same place:

![image](https://cloud.githubusercontent.com/assets/14843712/11753321/5045e540-9ff9-11e5-8b64-28d43f715d06.png)

**Comment by davisagli** [comment]
Maybe it's different because you're the group organizer. I'll look again.

**Comment by davisagli** [comment]
@ebskopin does it work now?

**Comment by ebskopin** [comment]
Yep, I'm seeing the E-mail field now. Thanks. It looks like the cancel buttons still aren't functioning.

**Comment by davisagli** [comment]
Right, we haven't gotten to the other parts yet. (It would have been nice to have 3 issues filed.)

**Comment by cewing** [comment]
I am taking on the first part of this issue.  I am unclear if the third part is resolved.  @mscholtz you removed the `Salesforce` label.  Does that mean that the error shown in part 3 above is resolved? Or does it mean that the problem isn't actually in Salesforce?

**Comment by mscholtz** [comment]
@cewing I honestly don't remember wnhy I removed the label.  But I think the error here was the one we've recently logged in #517 and I think will be resolved along w/ that ticket

**Comment by cewing** [comment]
Starting to poke at this and the reason that the button isn't working for group leaders is that the 'id' of the group contained in the group registration appears to be different than the id of the group in the list of groups associated with a work party.

For example, on the "Oregon Treaty Work Party" (http://staging.wta.org:6543/workparty/a2eK0000003Oyrd/), there is a group registered, the "Boeing Celebrates the Oregon Treaty" which has the ID `a2yK0000000E9iG`, however, when trying to cancel a registration the group_id associated with the registrations is not the same, it is `a2yK0000000E9iGIAS`.  Every registration for this particular party associated with this particular group has the same, incorrect ID for the group.  I am going to poke a bit further to try to discover why this is.

**Comment by cewing** [comment]
Okay.  The problem is now clear.  The two "different" ids for the same work party group are actually the 15-character and 18-character ids of the exact same work party group.  What this appears to mean is that although in the VMS app we are using (and storing) the 15-character form of this ID, the Salesforce service that registers users for work party groups is storing the 18-character form.  

I can confirm that when a registration is sent to the salesforce `createregistration` webservice the 15-character form of the ID is transmitted.  This is the registration information sent when I register bobby tables for the oregon treaty workparty:

```
{'firstName': u'Bobby',
 'lastName': u'Tables', 
 ...
 'workPartyId': u'a2eK0000003Oyrd', 
 'groupId': u'a2yK0000000E9iG'
 ...
}
```

But when the data about registrations for the workparty comes back at the point where we are trying to cancel the registration, the ID shown for the group is the 18-character form.  

It appears that we are not filtering this id to its shorter form when performing the `get_registrations` call on the salesforce client.  I am updating that method to truncate group IDs in registrations to 15 characters.

**Comment by mscholtz** [comment]
One thing to keep in mind: the 15 char ID is case sensitive.  The 18 char
ID is not (which is why they have the 18 char ID)

On Thu, Jan 7, 2016 at 12:57 PM, Cris Ewing <notifications@github.com>
wrote:

> Okay. The problem is now clear. The two "different" ids for the same work
> party group are actually the 15-character and 18-character ids of the exact
> same work party group. What this appears to mean is that although in the
> VMS app we are using (and storing) the 15-character form of this ID, the
> Salesforce service that registers users for work party groups is storing
> the 18-character form.
>
> I can confirm that when a registration is sent to the salesforce
> createregistration webservice the 15-character form of the ID is
> transmitted. This is the registration information sent when I register
> bobby tables for the oregon treaty workparty:
>
> {'firstName': u'Bobby',
>  'lastName': u'Tables',
>  ...
>  'workPartyId': u'a2eK0000003Oyrd',
>  'groupId': u'a2yK0000000E9iG'
>  ...
> }
>
> But when the data about registrations for the workparty comes back at the
> point where we are trying to cancel the registration, the ID shown for the
> group is the 18-character form.
>
> It appears that we are not filtering this id to its shorter form when
> performing the get_registrations call on the salesforce client. I am
> updating that method to truncate group IDs in registrations to 15
> characters.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/485#issuecomment-169802859>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by cewing** [comment]
hmmmmm.  Okay.  That's interesting.  It looks to me like we are often truncating the IDs returned to us by salesforce to 15 characters from the 18 characters SF is sending us.  My solution here was to do the same truncation for the 18-char id returned by the `get_registrations` method of our salesforce client. I've also discovered that the comparison of regId to the id in each registration [here](https://github.com/washingtontrails/vms/blob/master/src/vms/register.py#L594) is also failing when cancelling the registration of a group member.  Again, I've chosen simply to truncate both values to 15 characters to ensure that we have the same length value on each side of the comparison, but the fact that cancelation of someone else's registration has been working for some cases and not others leads me to believe that we do not have consistency in which type of ID we are looking at.  

I'm going to make a PR for this and ask @davisagli to take a careful look at it after I'm done.  I'm a bit concerned about the edge cases arising from my changes here.

**Comment by mscholtz** [comment]
Truncation is fine, as long as any string comparison you do in the code is
case-sensitive

On Thu, Jan 7, 2016 at 1:16 PM, Cris Ewing <notifications@github.com> wrote:

> hmmmmm. Okay. That's interesting. It looks to me like we are often
> truncating the IDs returned to us by salesforce to 15 characters from the
> 18 characters SF is sending us. My solution here was to do the same
> truncation for the 18-char id returned by the get_registrations method of
> our salesforce client. I've also discovered that the comparison of regId to
> the id in each registration here
> <https://github.com/washingtontrails/vms/blob/master/src/vms/register.py#L594>
> is also failing when cancelling the registration of a group member. Again,
> I've chosen simply to truncate both values to 15 characters to ensure that
> we have the same length value on each side of the comparison, but the fact
> that cancelation of someone else's registration has been working for some
> cases and not others leads me to believe that we do not have consistency in
> which type of ID we are looking at.
>
> I'm going to make a PR for this and ask @davisagli
> <https://github.com/davisagli> to take a careful look at it after I'm
> done. I'm a bit concerned about the edge cases arising from my changes
> here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/485#issuecomment-169807455>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by cewing** [comment]
It is.  What I'm a bit worried about is if we get an 18-character version of the ID sent to us that has different case than the sensitive 15-char version.  Maybe that's not a concern because SF never sends an 18-char version with cases switched, but I'm not comfortable asserting that is true on my own :)

**Comment by mscholtz** [comment]
The 15 char version of the ID for a record will never have any different
case chars than the first 15-chars of the 18-char version.  The 18-char ID
does not use arbitrary case.  That is not a concern.

They do this because some systems (e.g. Excel) don't have an easy option
for doing case-sensitive comparisons.  So if you use 18-char IDs you don't
have to worry about that.

But an ID that had a char with a different case would be for a different
record.



On Thu, Jan 7, 2016 at 1:20 PM, Cris Ewing <notifications@github.com> wrote:

> It is. What I'm a bit worried about is if we get an 18-character version
> of the ID sent to us that has different case than the sensitive 15-char
> version. Maybe that's not a concern because SF never sends an 18-char
> version with cases switched, but I'm not comfortable asserting that is true
> on my own :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/485#issuecomment-169808291>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by cewing** [comment]
Okay.  That goes a long way toward alleviating my concerns.  Thanks @mscholtz

**Comment by davisagli** [comment]
Part 1 of this should be fixed now.

**Comment by ebskopin** [comment]
These features now work.  Thank-you.
