### ISSUE TITLE
VMS: Volunteer Vacation Cost for 2nd or additional trips in one season

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#487]
We have a policy that volunteers who sign up for 2 or more Volunteer Vacations will get a discounted rate on the 2nd and additional trips.  Where do we set the "price" for these subsequent sign ups for a given volunteer?

If this feature doesn't exist we may need to prioritize this for next weeks mini development iteration.

**Comment by davisagli** [comment]
We haven't implemented this so far and I don't remember seeing stories about it.

Does next week's mini iteration include Percolator? Implementing this will require some work in Salesforce because the registration webservice would need to return the price for each volunteer depending on whether they meet the criteria for this pricing.

**Comment by mscholtz** [comment]
Closing this since there's now a story on the backlog (332)
