### ISSUE TITLE
VMS: Create website with VMS and production Salesforce data, eg vms.wta.org.

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#506]
@davisagli  We need to have a website where we can view the current VMS website as well as production salesforce data.  As I discussed with David perhaps this could be mybackpack@wta.org.

Purpose for this is to verify data entered into production salesforce.  This could be work parties, My Backpack information, etc.

**Comment by davisagli** [comment]
I started setting this up. I'm actually doing it on the production webserver, so it can become the live version of VMS once we're ready.

However, I'm currently blocked because www.wta.org is served via CloudFlare, so I need access to CloudFlare to set up vms.wta.org to point at VMS. (Or I can ask Steve to help with that tomorrow.)

**Comment by WaBirder57** [comment]
Yes Steve can help with this. Ccd him on this email.

Charlie

**Comment by davisagli** [comment]
@smcmahon what I'd like is to have vms.wta.org set up on CloudFlare to point at the production webserver, ideally with TLS termination but without caching actually enabled. Then I can adjust nginx on the webserver to proxy that domain to VMS. Will that work?

**Comment by smcmahon** [comment]
I'll set up the cloudflare side.

**Comment by smcmahon** [comment]
OK, questions.

By "production" webserver, did you mean www.wta.org? Or mybackpack?

If www, is there a reason why we can't use the www.wta.org or wta.org hostname? We already have certificates for that.

We probably can't use Cloudflare SSL w/o caching unless we're going to use some no-cache or immediate expiration messages.

**Comment by davisagli** [comment]
>By "production" webserver, did you mean www.wta.org? Or mybackpack?

www

> If www, is there a reason why we can't use the www.wta.org or wta.org hostname? We already have certificates for that.

We might be able to make it work with a subpath of www.wta.org, but it'll take some review of how urls are generated throughout the app since we were assuming it would be at the root of a domain. I thought that CloudFlare provided TLS for any domain, but maybe I have that wrong?

> We probably can't use Cloudflare SSL w/o caching unless we're going to use some no-cache or immediate expiration messages.

Okay, we can try it with caching on and I can add that caching header if necessary.

**Comment by smcmahon** [comment]
OK, we're set!

**Comment by smcmahon** [comment]
Sorry about the accidental close. Pushed the wrong button.

**Comment by davisagli** [comment]
@smcmahon http://vms.wta.org is working now, but https://vms.wta.org shows the wta.org homepage rather than VMS. The CloudFlare certificate is for *.wta.org so in theory we should be able to use it for both, but I'm not sure if we need to fix something in CloudFlare configuration (which I don't have access to presently) or apache configuration. Any ideas?

**Comment by smcmahon** [comment]
We ought to be able to do it via apache. Right now we're seeing www because it's the default site for the IP.

What do we need to reverse proxy (port)?

**Comment by davisagli** [comment]
@smcmahon I got it working by adding this to the existing SSL VirtualHost:

        RewriteCond %{HTTP_HOST} ^vms.wta.org$
        RewriteRule ^/(.*) http://127.0.0.1:6543/$1 [L,P]

**Comment by smcmahon** [comment]
Looks good.

**Comment by davisagli** [comment]
@WaBirder57 there is now an instance of VMS running at https://vms.wta.org which is connected to your production Salesforce instance. It's also connected to the live website for logging in, so you'll need to log in with your real wta.org accounts.

This is running on the production webserver and I anticipate turning it into the real live copy of VMS when we're ready to complete launching. Feel free to use it for testing that we've successfully configured everything in this new instance, but be much more careful to remove any test data when you're done since it goes into the live database!

There are still various things that we'll be working on setting up for this instance of VMS:
- Need to make it use your real Click and Pledge account
- Need to make it use FormAssembly forms that are configured to write to production Salesforce rather than the sandbox
- Need to update the ids of Salesforce folders to pull documents from for the Crew Leader Toolkit
- etc

**Comment by WaBirder57** [comment]
I assume that vms.wta.org is open to the public at this point and that any one could stumble across this or perhaps google it.  We aren't too worried about folks stumbling across this but I just wanted to verify my assumption on this.

**Comment by davisagli** [comment]
That's correct. Would you like me to add a robots.txt to block search engines from indexing it for now?

**Comment by WaBirder57** [comment]
Sure that would be good.  Thanks for thinking of this.

**Comment by davisagli** [comment]
Okay, robots.txt is in place.

I noticed there's an issue with logging in to vms.wta.org; it doesn't redirect back to VMS correctly. I'll look into it.

**Comment by WaBirder57** [comment]
I assume this problem is what is giving us problems actually registering for a work party on vms.wta.org.  If that is a different issue let us know and we can log it.

**Comment by davisagli** [comment]
@WaBirder57 you haven't described the registration issue so I don't know if it's the same. probably not. please file it as a full ticket describing what you did and what the problem was.

**Comment by ebskopin** [comment]
@WaBirder57 Wrote a ticket for what I'm experiencing

**Comment by davisagli** [comment]
Fixed
