### ISSUE TITLE
VMS: Youth Vol Vac Registration Bug

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#508]
When registering for a Youth Volunteer Vacation, when the "Register" button is clicked the page does not advance to the confirmation page. If you refresh the page and click the "Register" button again the following message appears:

![image](https://cloud.githubusercontent.com/assets/14843712/12126156/52324a9c-b3a4-11e5-9417-5383e497c7dc.png)

This error seems distinctive to youth volunteer vacations.

**Comment by davisagli** [comment]
Please give me the URL of the particular work party you were testing

David Glick
(mobile)

**Comment by ebskopin** [comment]
http://staging.wta.org:6543/workparty/a2eK00000000uUr/

**Comment by davisagli** [comment]
It's breaking because the work party type has "Costs Money" checked (which makes it load the payment form) but the work party does not have fees set (see https://cs9.salesforce.com/a2eK00000000uUr). You might want to add some validation to make sure that a work party has fees set if its Work Party Type has "Costs Money" checked.

**Comment by ebskopin** [comment]
gotcha, thanks.
