### ISSUE TITLE
VMS: Youth Vol Vac CL Registration Bug

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#509]
When attempting to register a New WP Registration for a CL or ACL in Salesforce for a Youth Volunteer Vacation the following error occurs, even if the contact has a current Background Check: 

![image](https://cloud.githubusercontent.com/assets/14843712/12126631/2e20c860-b3a7-11e5-9477-d98538f928a6.png)

In this instance I am attempting to register Andrea Martin -https://cs9.salesforce.com/003K0000016Tuxv as the CL for this YVV - https://cs9.salesforce.com/a2eK00000000uUr

@mscholtz

**Comment by mscholtz** [comment]
@ebskopin did you update Andrea's background check fields recently (since I ran the data migration)?
The code is looking for a WP Volunteer Certification record of type "Background Check", not a value in the old fields (which we will hopefully be deleting at some point).

The certification rec should have been created during the migration, but wouldn't have been if someone entered it since then.

**Comment by ebskopin** [comment]
Ah, thanks for the reminder. I did some editing of the field, as did she, so there was likely something in place that didn't create the WP Volunteer Certification record. I've updated her WP Volunteer Certification and the error is no longer thrown.
