### ISSUE TITLE
VMS: Question on VMS (Pryamid) vs Plone Accounts on Staging.WTA.Org

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#515]
Using charles@wta.org when I log into staging.wta.org I have a user account that is different from the account on staging.wta.org:6543.  Different user profile etc.

Can these accounts be synced or merged?

Question for testers setting up MyBackpack accounts: Should new testers set up their account at staging.wta.org OR staging.wta.org:6543

Thank you.

**Comment by davisagli** [comment]
The staging VMS site (staging.wta.org:6543) is connected to the mybackpack.wta.org Plone site, not to the staging.wta.org Plone site (because so far we have not enabled the VMS-related features on staging.wta.org). So testers can set up their accounts starting from either staging.wta.org:6543 or mybackpack.wta.org, but not staging.wta.org.

**Comment by WaBirder57** [comment]
Thanks.
