### ISSUE TITLE
Workparty Map view - showing mulitple work parties at the same location

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#52]
Not sure how multiple work parties at the same location should be displayed.  If the option is only for a single map point then clicking on the map point should pop up information for the next available work party at that location.  Ideally at tiled display would pop up just showing the top part of what is displayed now with Name, Date and add work party type.  During peak season many (>12) work parties could be posted for a given location.  We need to think through how that would be displayed.

**Comment by alecpm** [comment]
Could you explain what you mean by a tiled display in this case?  Would this be within the info window that pops up when you click a single marker?  Perhaps a simple row for each work party at that location?  That might be tricky, since it would involve combining the work parties for a given point into a single customized html entry for the marker window.

One option would be to disambiguate the map points a bit by adding a random fuzz to the lat/long values (spreading them within 100m radius or similar) when adding them to the map.  That would make it easier to see each work party in detail from the map view by zooming in, but it wouldn't provide a means of highlighting the next available work party for the location, which does seem like it would be valuable.

Similarly, we could use a library to spread the points out when clicked:

https://github.com/jawj/OverlappingMarkerSpiderfier

Example here:

http://www.ejw.de/ejw-vor-ort/

**Comment by davisagli** [comment]
I was thinking it might not be too bad to combine co-located work parties and add a single marker for them, with the info window listing all the work parties in that location. There aren't going to be more than a few hundred total so I doubt this would be a big problem to do in WorkPartyMap's componentDidMount/componentDidUpdate

**Comment by alecpm** [comment]
That would be best in terms of allowing for explicit ordering of the items, though it might get a bit awkward in the UI for >12 work parties (of course so would multiple pins, but in a different way).

**Comment by WaBirder57** [comment]
Check out the current WTA hike finder map where we have this same issue  http:/www.wta.org/go-hiking/map <http://www.wta.org/go-hiking/map> .  Multiple hikes starting from the same location.  Here a mouse over the GPS pin opens a pop up, tool tip like box, with brief info each item (hike) as well as a clickable link to that hiking guide entry.

**Comment by davisagli** [comment]
Charlie, what's an example of a location on the hike finder map that has multiple hikes?

**Comment by WaBirder57** [comment]
If you are zoomed out, as when you first land on the page, most any spot will show multiple hikes in the pop up tool tip.

 

Also I see: Tiger Mountain South Trail and Tiger Mountain Trail are collocated.  Search on “Tiger Mountain Trail”, pick the spot to the south of tiger mtn.

 

Thus as you zoom in it is able to disaggregate the points if they are close but not “really” at the same spot on the map.

**Comment by davisagli** [comment]
Oh, I see. Alec, It looks like for the hike finder map that's being handled by this code which groups hikes that are located close together: https://github.com/washingtontrails/wta.content/blob/master/wta/content/skins/wta_content/HikeFinder.js#L317

**Comment by WaBirder57** [comment]
We should probably have a cool little Work Party icon to use also rather than generic Map pin.  Correspond to the Hiker we use on the Hike Finder Map.  I will see what I can find but if you needed something right now can you use that hiker icon from the hike finder map?

**Comment by davisagli** [comment]
Maybe Ethical UX can suggest a map marker icon that would work well with the design.

**Comment by WaBirder57** [comment]
Yes, we are hoping to use the icon they design for our hard hat awards.  So work in process at this point.

**Comment by alecpm** [comment]
Implemented an info window with combined work parties in commit 9230d818eabadebe8834880611e985b0a4a8b674

**Comment by skleinfeldt** [comment]
@alecpm can you confirm this is deployed to staging and ready to test?

**Comment by skleinfeldt** [comment]
The consensus here is that this has been deployed, so go ahead and test @WaBirder57

**Comment by WaBirder57** [comment]
This is working, thanks.
