### ISSUE TITLE
VMS: Need validation that work party has an end date

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#521]
When attempting to view my "Completed" or "Summary Report Needed" WPs in my MBP account I receive the following error: 

![image](https://cloud.githubusercontent.com/assets/14843712/12211133/f0b73544-b613-11e5-9e65-43717c1c9236.png)

I am working with this MBP account: https://cs9.salesforce.com/003K0000015g4x9.

**Comment by davisagli** [comment]
Looks like it's breaking when there are no results.

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module wta.content.backpack.backpack, line 1019, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__ 
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__  
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in __call__
  Module z3c.pt.pagetemplate, line 149, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 171, in render
  Module 051a30ba0a0384ebb6cf8f8d04e28d2f, line 1686, in render
  Module ca8eeb0be321cbd687a2bfc1f3de8f1f, line 1399, in render_master
  Module 051a30ba0a0384ebb6cf8f8d04e28d2f, line 1114, in __fill_content
  Module chameleon.tal, line 471, in __call__
  Module Products.CMFPlone.PloneBatch, line 140, in __getitem__
KeyError: 0
```

**Comment by davisagli** [comment]
Ah no, actually it's an error in the VMS app when it tries to read the user's work parties, and that error was not being reported in a useful way. The real problem is that this work party is missing an end date: https://cs9.salesforce.com/a2eK00000000tppIAA

(@mscholtz shouldn't we have a validation rule to prevent that?)

**Comment by ebskopin** [comment]
Huh, good catch.  When I adjusted that work-party my completed work parties displayed properly.  I agree that there should be a validation rule preventing that...

**Comment by mscholtz** [comment]
I looked into this, and we did originally have a validation rule for this, but it was deactivated back in April because we wanted the End Date to be able to be set based on the default in the WP Type.  And if it's always required, that won't work b/c you have to save it initially without any value.  
https://www.scrumdo.com/projects/project/wta/iteration/126630#story_923618

However, it is required in order to Publish a WP.  So I don't think this will be an issue in production going forward.  Looks like the WP in question is still in status "Planning", and registrations were added via SF. 

If we think there's a risk of the same thing happening in production, then I might suggest validation that would require an End Date before adding any registrations, even for CL/ACL.  Or @davisagli could you just make your code tolerant of missing end dates?

**Comment by davisagli** [comment]
Got it. Looks like part of the problem is that this screen was including Planning work parties when it should only include Published. Fixed.

**Comment by ebskopin** [comment]
Looks good.
