### ISSUE TITLE
VMS: Photo Credits Not Displaying

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#526]
A few instances in which the photo credits need to be displayed on the image:

The VMS Banner: Here is the current banner (http://mybackpack.wta.org/volunteer/vms-banners/vms-banner). Image caption is entered but does not appear anywhere on the actual banner - 
![image](https://cloud.githubusercontent.com/assets/14843712/12246030/e4d9cc42-b860-11e5-90ae-f58953ff3023.png)

Crew Leader Corner Landing Page: Image is displayed, but the image caption does not appear (http://mybackpack.wta.org/crew-leader-corner/edit).

**Comment by davisagli** [comment]
Both fixed.

For the VMS banner I wasn't sure if you wanted the credit at the bottom of the image since it might distract from the other text overlaid on the image, so I made it a tooltip instead. Hope that's all right.

I also copied that VMS banner to the live website (http://www.wta.org/volunteer/vms-banners/welcome) so it appears on the live copy of VMS.

**Comment by ebskopin** [comment]
That looks good. Thanks.
