### ISSUE TITLE
When crew leader is assigned to a work party a registration should be created for that person.

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#56]
When a crew leaders is assigned to a work party in Salesforce a registration should be created for that person on the work party.

For a Work Party in Salesforce when a contact is entered as the Crew Leader they are not added as a registered part of the crew.  If that person then (the crew leader) goes to Pyramid they are not able to see the roster for the trip, nor send emails.  They can sign up to join the trip but not as the Crew Leader.

This is related to Story #47, since the CL can't register for a work party we can't test sending out messages to the crew.

**Comment by davisagli** [comment]
Suggested workarounds that we discussed today:
1. In addition to filling in the Crew Leader lookup field, also create a Registration for the contact in Salesforce, making sure that it has work party role = Crew Leader and status = Registered. Then log in to VMS as that contact and it should be considered a crew leader who can send messages.

OR

2. Register in VMS as a volunteer or ACL. Then, in Salesforce, find that registration and change the work party role to Crew Leader. In VMS log out and back in (this is necessary because the user's registrations are fetched from Salesforce when the user logs in) and now you should have crew leader access to the work party.

**Comment by WaBirder57** [comment]
Thank, these workarounds work.  I'll change the tags on this issue.  Did we decide that this needed to be its own story?

**Comment by mscholtz** [comment]
I would like it to be a story, simply because it will likely take more time than we typically have per-person for tickets.  And it's not a bug on something we already worked on, it's a new requirement.

Just created story 201: https://www.scrumdo.com/projects/project/wta/iteration/110416#story_923826 so I think we can close this

**Comment by WaBirder57** [comment]
New Story created: story 201
