### ISSUE TITLE
Work Party Type has default Start and End TIME for work party

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#91]
Add to the Work Party Type object a default work party start and end time fields.  When a new work party is created and saved using this work party type, the default start and end time will be set for the work party based on these values.  This start and end time for the Work Party can then be changed for that individual work party if needed.

**Comment by drewpiston** [comment]
Hi Charlie @WaBirder57 ,

Right now the Work Party object has hardcoded defaults to start time of 8:30 and end time of 3:30.  Is it ok to remove these defaults?

The behavior would then be:
1. Null values get set to Work Party Type defaults on save
2. Non-null values persist through save.

PS @mscholtz I had to do this in a before trigger because SF can't handle workflow updates to picklist fields gracefully.

**Comment by WaBirder57** [comment]
Yes, I think this would be ok.  Staff will learn that they need to create and then Save a new WP to get various settings.  Then they can edit it again to add or adjust other values in the WP.

**Comment by WaBirder57** [comment]
Looks good.
