### ISSUE TITLE
Work Party Capacity: Volunteer limit not enforced

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#99]
In a work party set the Capacity to 5 and volunteer capacity to 3.  Add more than 3 volunteer registrations in Salesforce.  The limit of 3 volunteers doesn't seem to do anything to prevent adding more volunteers.   Is this a pyramid only limit?

Example work party: Evans Creek 5/23.  https://cs9.salesforce.com/a2eK0000000wL7P?newid=a2oK0000000sWaU

Note that when the total work party capacity is exceeded new registrations are set to "Waitlist".  I would expect the same behavior for volunteer in excess of the volunteer limit.

**Comment by davisagli** [comment]
I think this is working now (probably thanks to the work that was done for issue #134). I added a registration for myself to this work party with status set to Registered, and it changed it to Waitlisted.

**Comment by ebskopin** [comment]
I am still finding that the capacity set in Salesforce for a WP is not reflected correctly.  Example: Pinnacle Peak - http://staging.wta.org:6543/workparty/a2eK00000000j5Q/ indicates that there is 1 spot available when it should actually be wait-list only (SF WP - https://cs9.salesforce.com/a2eK00000000j5Q). It seems that both on the Salesforce side and on the registration page it is taking the "Capacity" field into consideration rather that the "Volunteer Capacity" field.

**Comment by davisagli** [comment]
There's one spot available because there's no registration for a Crew Leader on that work party, and it holds one space for the CL.

**Comment by ebskopin** [comment]
Even with a crew leader registered it still indicates that one spot is available on the VMS registration page for some reason (https://cs9.salesforce.com/a2eK00000000j5Q?newid=a2oK00000003HLC). If a 4th Volunteer is registered then the capacity drops to 0, which is strange since that is 4 vols to the 3 vol capacity.

**Comment by davisagli** [comment]
@mscholtz I think one of you will have to take a look.

**Comment by mscholtz** [comment]
I think you guys are correct, this is not working.  Furthermore, I think the code was never written to take this into account.  Probably a miscommunication between Nineta and myself at some point.  Sorry!  And we suspect that David was looking at something he different when  he thought this was working back in June.

So we will get to this ASAP, but probably not until the formal QA process for MBP begins.  Let us know if waiting for a few weeks is a problem.

**Comment by mscholtz** [comment]
note to self: there is no mechanism at all to consider this when assigning waitlist status.  looks like easiest fix is to include this in the Waitlist Volunteers Only formula, that should trigger the action we want.  also write a test.

**Comment by mscholtz** [comment]
for self:

- [ ] redo formula for Waitlist Volunteers Only
- [ ] respect WVO on insert
- [ ] respect WVO on update

**Comment by mscholtz** [comment]
@ebskopin one question here.  The possibility exists that in a friends/family party, we could have one or more volunteers and also one or more ACLs.  (In fact we recently updated how this works, see ticket #79)

In general the way waitlisting works is that there's either room for the entire party or there's not.  And if not, it puts them all on the waitlist, even if there would be room for some of them.  (They may be split up later if they indicated they're willing, but we don't split them up initially)

So w/ regards to the Volunteer Capacity, what happens if it's a mixed party of Vols and ACLs?  Do we still have to check separately if there's room in the Vol Capacity for the vols in the party?   In addition to checking that there's space in the overall capacity for everyone?

And if so, if there's not room for the vols, can we waitlist the entire party?  Including the ACLs?

**Comment by ebskopin** [comment]
Hmm. In that instance, I would say we treat the entire group as if they are all vols. Meaning, if a group signs up and has 2 ACLs and 3 vols, and there are only spots for 4, we wait-list the entire group. The ACLs should be familiar enough with the system to know that if they really want to go they can register separately, and the likelihood of ACLs signing up as parts of groups is pretty low. Does that answer your questions? Thanks.

**Comment by mscholtz** [comment]
@ebskopin yep, seems good.  I'll do it that way.  Thanks!

**Comment by mscholtz** [comment]
This is done.  It was actually easy enough to go one step further than what you said was OK, @ebskopin .  In a mixed party of vols and leaders, it will could how many vols are in the party, and see if there are room for them within the Volunteer Capacity.  But if there isn't, it will waitlist everyone, including the ACLs.

Note that this only is properly enforced for new registrations, not for those being invited from the waitlist.  (see #448)

**Comment by ebskopin** [comment]
This is now working, thanks.
